### ISSUE TITLE
BTC.com support of Modern Soft Fork Activation

### ISSUE THREAD

**Issue by michaelfolkson** [taprootactivation/Taproot-Activation#10]
Was the BTC.com support of Modern Soft Fork Activation declared in private communication? There doesn't appear to be a coinbase signal or proof of support stated on the website?

**Comment by AlejandroDeLaTorre** [comment]
Yes, it was in private, i'll send BTC.com team this thread so they can confirm.

**Comment by michaelfolkson** [comment]
Awesome, thank you. When you do can you also enquire on whether they would be open to revised BIP 8 as an alternative? 

At least on the mining pool side that seems to be the preferred option at this stage. Unsure on how strong there is a preference for BIP 8(false, 1 year) specifically.

Thanks for your help and for your site, much appreciated.

**Comment by haohailuo** [comment]
BTC.com is considering the way to support the main root, which is the support of modern soft fork activation, but will also consider the revised BIP 8 (false, 1 year).
We will soon release announcement regarding it.

**Comment by AlejandroDeLaTorre** [comment]
hey @haohailuo please review https://www.coindesk.com/taproot-speedy-trial-code-merged-into-bitcoin-core if need be contact me thru weixin - am in contact with Irina, thank you.

**Comment by michaelfolkson** [comment]
Thanks @AlejandroDeLaTorre. In addition there was coverage in [Bitcoin Optech](https://bitcoinops.org/en/newsletters/2021/04/21/) and [Bitcoin Magazine](https://bitcoinmagazine.com/technical/there-are-now-two-taproot-activation-clients-heres-why). Feel free to contact me if you have any questions.

**Comment by michaelfolkson** [comment]
[This](https://bitcoincore.org/en/2016/06/08/version-bits-miners-faq/) might be helpful too. It is a FAQ for miners on version bits that was used for past soft forks. Some of it is outdated (e.g. BIP number, Speedy Trial specifics) but the version bits guidance should still apply.

**Comment by mutatrum** [comment]
BTC.com has mined block 682015 with taproot signalling: https://mempool.space/block/0000000000000000000a040a5922fc8328d5a05b6e7f6a9a16fb8291685486b4

**Comment by michaelfolkson** [comment]
@mutatrum: Thanks, that's great! It is important that **all** (or as many as possible) blocks mined by BTC.com signal if we are going to meet the 90 percent threshold of blocks needed to activate Taproot in a signaling period. Thanks for letting us know about the first block mined by BTC.com that is signaling for Taproot though :)

**Comment by charlespax** [comment]
Can this issue be closed?

Here is an announcement on Twitter on May 13th (https://twitter.com/btccom_official/status/1392735570019766272?s=20)
