### ISSUE TITLE
Proofs?

### ISSUE THREAD

**Issue by AbelLykens** [taprootactivation/Taproot-Activation#5]
Could we link to tweets/site/... as a proof of taproot support? 

Not everyone is signalling I suppose (not in the last place because there is no proposal, right?). 

So some proof would be nice, in the table.

**Comment by AlejandroDeLaTorre** [comment]
The section in the table 'Coinbase Signal' was intended to provide just that, "proof". So far, only Poolin has tagged a coinbase block with Taproot/BIP9. I want to give the other pools a tad more time. Let's see how it develops. Thanks for the feedback.

**Comment by AbelLykens** [comment]
Yeah of course we want Signalling: The Bitcoin Way.

But until then, link to twitter/site?

**Comment by AlejandroDeLaTorre** [comment]
Good idea, will do. Thanks again

**Comment by oliverkane** [comment]
I was actually going to open a ticket a moment ago till I read this one. I was going to ask for something adjacent: "more info". Proofs are largely the same thing as I was seeking. Essentially, I suspect this project will garner a lot of attention like my own, and I hunger for more details, but there's scant to be had.  

Happy to put together a PR if there's raw sources you'd rather just dump here in the thread.

**Comment by AlejandroDeLaTorre** [comment]
Proof of Support section on the table has been created.
