### ISSUE TITLE
% support

### ISSUE THREAD

**Issue by AbelLykens** [taprootactivation/Taproot-Activation#6]
Is there a way we can have total % support for Taproot? 

Challenge is that these numbers are dynamic probably... But an estimation would be cool.

**Comment by AlejandroDeLaTorre** [comment]
Another good idea, will add.

**Comment by moneyball** [comment]
Or % hash rate that does NOT support it (and would love to see the rationale stated as to why, otherwise that isn't very useful feedback for the ecosystem).
